version: '3'

services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: gamer
      MONGO_INITDB_ROOT_PASSWORD: games
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: gamer
      ME_CONFIG_MONGODB_ADMINPASSWORD: games
    ports:
      - 3064:8081
